name: ci-wf
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6
      - name: Install Dev Dep
        run: npm install
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"
      - name: Lint CSS Files
        run: npx stylelint "**/*.css"
  app-build-job:
    runs-on: ubuntu-latest
    # needs: "linting-job"
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6
      - name: Install Dev Dep
        run: npm install
      - name: Build Website With Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./" --no-cache
  image-build-job:
    needs: "app-build-job"
    runs-on: ubuntu-latest
    steps:
      - name: clone Repo
        uses: actions/checkout@v6
      - name: Login To Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        run: docker image build -t ${{ secrets.DOCKERHUB_USERNAME }}/g4w13:latest . 
      - name: List the Images
        run: docker image ls
      - name: Push Docker Image on DH
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/g4w13:latest
        
    



